language: python
python:
  - "2.7"
env:
  - DJANGO=1.7
install:
  - pip install -q -e . --use-mirrors
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q -e . --use-mirrors
script:
  - python server/manage.py test
